CREATE TABLE PEOPLE
(ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(50) DEFAULT "JOHN",
	AGE INT NOT NULL,
    ROLL VARCHAR(50) DEFAULT "EMPLOYED");
    
INSERT INTO PEOPLE 
(NAME , AGE)
VALUE ("DIVY" , 22);

INSERT INTO PEOPLE (NAME , AGE)
VALUE ("HET" , 18),
	("JENIL" , 21),
    ("RAJ" , 21);

UPDATE PEOPLE SET NAME = "BHAUTIK"
WHERE NAME = "JENIL";

SELECT CONCAT(AUTHOR_FNAME , ' ', AUTHOR_LNAME)FROM BOOKS;

SELECT SUBSTRING(AUTHOR_FNAME , 1 , 5) FROM BOOKS;

SELECT CONCAT(SUBSTRING(AUTHOR_FNAME , 1 , 5),'...')FROM BOOKS;

SELECT REPLACE("HELLO WORLD" , "H" , "E");

SELECT * FROM BOOKS ORDER BY AUTHOR_FNAME;

SELECT REVERSE(AUTHOR_FNAME) FROM BOOKS;

SELECT CHAR_LENGTH(AUTHOR_FNAME) FROM BOOKS;

SELECT UPPER(AUTHOR_FNAME) FROM BOOKS;

SELECT LOWER(AUTHOR_LNAME) FROM BOOKS;

SELECT DISTINCT(AUTHOR_FNAME) FROM BOOKS;

SELECT DISTINCT CONCAT(author_fname,' ', author_lname) FROM books;

SELECT DISTINCT CONCAT(author_fname,' ', author_lname) FROM books LIMIT 5;

SELECT * FROM BOOKS WHERE AUTHOR_FNAME LIKE "%DA%";

SELECT COUNT(*) FROM BOOKS;

SELECT AUTHOR_FNAME , COUNT(AUTHOR_FNAME) FROM BOOKS GROUP BY AUTHOR_FNAME;

SELECT MAX(PAGES) FROM BOOKS;

SELECT MIN(PAGES) FROM BOOKS;

SELECT * FROM books 
WHERE released_year = (SELECT MIN(released_year) FROM books);

SELECT CONCAT(author_fname, ' ', author_lname) AS author,  COUNT(*)
FROM books
GROUP BY author;

SELECT 
	author_lname, 
	COUNT(*) as books_written, 
	MAX(released_year) AS latest_release,
	MIN(released_year)  AS earliest_release,
	MAX(pages) AS longest_page_count
FROM books GROUP BY author_lname;

SELECT author_lname, COUNT(*), SUM(pages)
FROM books
GROUP BY author_lname;

SELECT 
    released_year, 
    AVG(stock_quantity), 
    COUNT(*) FROM books
GROUP BY released_year;

SELECT * FROM BOOKS
WHERE AUTHOR_FNAME != "DAVID";

SELECT * FROM BOOKS
WHERE AUTHOR_FNAME NOT LIKE "%NE%";

SELECT * FROM BOOKS 
WHERE RELEASED_YEAR > 2001;

SELECT * FROM BOOKS
WHERE RELEASED_YEAR < 2001;

SELECT * FROM BOOKS
WHERE AUTHOR_LNAME = "EGGERS"
AND RELEASED_YEAR > 2010
AND TITLE LIKE "%NOVEL%";

SELECT * FROM BOOKS
WHERE AUTHOR_LNAME = "EGGERS"
OR RELEASED_YEAR > 2010;

SELECT * FROM BOOKS
WHERE RELEASED_YEAR BETWEEN 2004 AND 2015 ORDER BY RELEASED_YEAR;

SELECT * FROM BOOKS
WHERE RELEASED_YEAR NOT BETWEEN 2004 AND 2015 ORDER BY RELEASED_YEAR;

SELECT * FROM BOOKS
WHERE AUTHOR_LNAME IN("LAHIRI" , "SMITH" , "CARVER");