-- TO MAKE TABLE
CREATE TABLE PEOPLE
(ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(50) DEFAULT "JOHN",
	AGE INT NOT NULL,
    ROLL VARCHAR(50) DEFAULT "EMPLOYED");

-- TO INSERT DETAILS    
INSERT INTO PEOPLE 
(NAME , AGE)
VALUE ("DIVY" , 22);

INSERT INTO PEOPLE (NAME , AGE)
VALUE ("HET" , 18),
	("JENIL" , 21),
    ("RAJ" , 21);

-- TO UPDATE TABLE
UPDATE PEOPLE SET NAME = "BHAUTIK"
WHERE NAME = "JENIL";