 -- --FINDING 5 OLDEST USERS
 SELECT * FROM USERS ORDER BY created_at limit 5;
 
 -- --MOST POPULAR REGESTRATION DATE
SELECT dayname(CREATED_AT) AS DAY , COUNT(*) AS TOTAL FROM USERS GROUP BY DAY ORDER BY TOTAL DESC LIMIT 2;

-- --IDENTIFY INACTIVE USERS
SELECT * FROM USERS LEFT JOIN PHOTOS ON USERS.ID = PHOTOS.USER_ID WHERE USER_ID IS NULL;

-- --IDENTIFY MOST POPULAR PHOTO
SELECT photos.id,photos.image_url,count(*) FROM PHOTOS JOIN LIKES ON PHOTOS.ID = LIKES.photo_id JOIN USERS ON USERS.ID = PHOTOS.USER_ID GROUP BY PHOTOS.ID ORDER BY COUNT(*) DESC LIMIT 1;

-- --CALCULATE AVG NUM OF POSTS
SELECT (SELECT COUNT(*) FROM PHOTOS) / (SELECT COUNT(*) FROM USERS);

-- --FIVE MOST POPULAR HASHTAGS
SELECT tags.tag_name, Count(*) FROM TAGS JOIN PHOTO_TAGS ON TAGS.ID = photo_tags.tag_id GROUP BY TAGS.ID ORDER BY COUNT(*) DESC LIMIT 5 ;

-- --FINDING BOTS
SELECT USERNAME , USER_ID,COUNT(*) FROM USERS JOIN LIKES ON USERS.ID = LIKES.USER_ID GROUP BY LIKES.USER_ID HAVING COUNT(*)=257;