-- --TO CREATE VIEW 
CREATE VIEW ORDERED_SERIES AS SELECT * FROM SERIES ORDER BY RELEASED_YEAR;

-- --IF VIEW IS ALREADY EXISTS AND YOU WANT TO CHANGE ANYTHING IN FILE YOU CAN USE REPLACE VIEW
CREATE OR REPLACE VIEW ORDERED_SERIES AS SELECT * FROM SERIES ORDER BY RELEASED_YEAR DESC; 

-- --ALTERING VIEW
ALTER VIEW ordered_series AS
SELECT * FROM series ORDER BY released_year;
 
 -- --TO DELETE VIEW
DROP VIEW ordered_series;

-- --HAVING CLAUSE
SELECT TITLE , AVG(RATING) FROM FULL_REVIEWS GROUP BY TITLE HAVING title = "Archer";
SELECT TITLE , AVG(RATING),COUNT(RATING) FROM FULL_REVIEWS GROUP BY TITLE HAVING COUNT(RATING)>1;

-- --WITH ROLLUP
SELECT TITLE , AVG(RATING) , COUNT(RATING) FROM FULL_REVIEWS GROUP BY TITLE WITH ROLLUP;
SELECT  first_name, released_year, genre, AVG(rating) FROM full_reviews GROUP BY released_year , genre , first_name WITH ROLLUP;


-- --SQL MODE BASICS
SELECT @@GLOBAL.sql_MODE;
SELECT @@SESSION.sql_MODE;

-- --TO REMOVE ALL MODE
SET SESSION sql_mode ="";

SET SESSION sql_mode ="ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,,NO_ENGINE_SUBSTITUTION";